version: 0.2

phases:
  pre_build:
  commands:
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 247893369505.dkr.ecr.ap-south-1.amazonaws.com

build:
  commands:
    - docker build -t brain-task-app .
    - docker tag brain-task-app:latest 247893369505.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest

post_build:
  commands:
    - docker push 247893369505.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest
